apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: northwindstore
    component: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: northwindstore
      component: app
  template:
    metadata:
      labels:
        app: northwindstore
        component: app
    spec:
      containers:
      - name: northwindstore-app
        image: dotnetcollege.azurecr.io/northwindstore/app:1.0
        ports:
        - containerPort: 80