version: '3.4'

services:
  northwindstore.app:
    image: ${DOCKER_REGISTRY-}northwindstoreapp
    build:
      context: .
      dockerfile: NorthwindStore.App/Dockerfile
  northwindstore.db:
    image: ${DOCKER_REGISTRY-}northwindstoredb
    build:
      context: ../labs/01/sql
      dockerfile: Dockerfile
